CREATE TABLE restic_summary_msg (
    changed_snapshots BIGINT,
    files_new BIGINT,
    files_changed BIGINT,
    files_unmodified BIGINT,
    dirs_new BIGINT,
    dirs_changed BIGINT,
    dirs_unmodified BIGINT,
    data_blobs BIGINT,
    tree_blobs BIGINT,
    data_added BIGINT,
    data_added_packed BIGINT,
    total_files_processed BIGINT,
    total_bytes_processed BIGINT,
    total_duration DOUBLE PRECISION,
    backup_start TIMESTAMP WITH TIME ZONE,
    backup_end TIMESTAMP WITH TIME ZONE,
    snapshot_id TEXT,
    hostname TEXT,
    sshid TEXT,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT now(),
    src TEXT,
    target TEXT,
    status TEXT,
    PRIMARY KEY snapshot_id
);
