name: test

trigger:
  on_push:
    branches: [main]
  on_pr:
    target: [main]

steps:
  - name: test
    env: .moira/envs/rust.nix
    run: |
      rustup default nightly
      cargo check
      cargo test
    vars:
      CARGO_TERM_COLOR: always

  - name: audit
    env: .moira/envs/rust.nix
    run: |
      rustup default nightly
      cargo install cargo-audit
      cargo audit --ignore RUSTSEC-2023-0071
    vars:
      CARGO_TERM_COLOR: always
