when:
  - event: push
    branch: main

steps:
  - name: build
    image: woodpeckerci/plugin-docker-buildx
    settings:
      platforms: linux/amd64,linux/arm64
      repo: git.hydrar.de/jmarya/bk
      registry: git.hydrar.de
      tags: latest
      username: jmarya
      password:
        from_secret: registry_token