when:
  - event: push
    branch: nix
depends_on:
  - container

steps:
  merge-manifest:
    image: quay.io/buildah/stable
    environment:
      REGISTRY_URL: "git.hydrar.de"
      REGISTRY_USER: "jmarya"
      REGISTRY_PASS:
        from_secret: registry_token
      IMAGE_NAME: "bk"
      BASE_TAG: "latest"
    commands:
      - buildah login -u "$REGISTRY_USER" -p "$REGISTRY_PASS" "$REGISTRY_URL"
      - export IMAGE_BASE="$REGISTRY_URL/$REGISTRY_USER/$IMAGE_NAME"
      - buildah manifest create "$IMAGE_BASE:$BASE_TAG"
      - buildah manifest add "$IMAGE_BASE:$BASE_TAG" "docker://$IMAGE_BASE:$BASE_TAG-amd64"
      - buildah manifest add "$IMAGE_BASE:$BASE_TAG" "docker://$IMAGE_BASE:$BASE_TAG-arm64"
      - buildah manifest push --all "$IMAGE_BASE:$BASE_TAG" "docker://$IMAGE_BASE:$BASE_TAG"
