matrix:
  platform:
    - linux/amd64
    - linux/arm64

labels:
  platform: ${platform}

when:
  - event: push
    branch: main

steps:
  - name: "Build & Push Container"
    image: harbor.vdx.hu/voidcontext/woodpecker-plugin-nix-attic:0.2.0
    environment:
      BINARY_CACHE_URL: "https://attic.hydrar.de"
      BINARY_CACHE_KEY: "some-public-key"
      BINARY_CACHE_TOKEN:
        from_secret: binary_cache_access_token
      REGISTRY_URL: "git.hydrar.de"
      REGISTRY_USER:
        from_secret: registry_user
      REGISTRY_PASS:
        from_secret: registry_pass
    settings:
      binary_cache: ${BINARY_CACHE_URL}
      binary_cache_public_key: ${BINARY_CACHE_KEY}
      binary_cache_token: ${BINARY_CACHE_TOKEN}
    commands:
      # Build the container image with Nix
      - nix build .#containerImage

      # Log in to the attic binary cache
      - attic login default ${BINARY_CACHE_TOKEN}

      # Push the Nix result to attic
      - "attic push some-cache $(nix path-info .#default)"

      - "IMAGE_TAG=$(nix run nixpkgs#skopeo -- list-tags docker-archive:$(realpath result) | nix run nixpkgs#jq -- -r .Tags[0])"

      # Push the built container image to the registry using skopeo
      - "nix run nixpkgs#skopeo -- copy docker-archive:$(realpath result) docker://${REGISTRY_URL}/${REGISTRY_USER}/${IMAGE_TAG} --dest-creds ${REGISTRY_USER}:${REGISTRY_PASS}"
