matrix:
  platform:
    - linux/amd64
    - linux/arm64

labels:
  platform: ${platform}

when:
  - event: push
    branch: nix

steps:
  - name: "Build & Push Container"
    image: nixos/nix:latest
    environment:
      BINARY_CACHE_URL: "https://attic.hydrar.de"
      BINARY_CACHE_KEY: "jmarya:J1TbOhfJf5efnN9bqcffa25hQ0pGaiRCP5njs4tDgaM="
      BINARY_CACHE_TOKEN:
        from_secret: binary_cache_access_token
      BINARY_CACHE_NAME: jmarya
      REGISTRY_URL: "git.hydrar.de"
      REGISTRY_USER: "jmarya"
      REGISTRY_PASS:
        from_secret: registry_token
    commands:
      - "echo -e \"\nexperimental-features = nix-command flakes\" >> /etc/nix/nix.conf"
      - "nix run nixpkgs#attic-client -- use $BINARY_CACHE_NAME"
      - "nix build .#containerImage"
      - "nix run nixpkgs#attic-client -- login default ${BINARY_CACHE_URL} ${BINARY_CACHE_TOKEN}"
      - "nix run nixpkgs#attic-client -- push $BINARY_CACHE_NAME $(nix path-info .#default)"
      - "IMAGE_TAG=$(nix run nixpkgs#skopeo -- list-tags docker-archive:$(realpath result) | nix run nixpkgs#jq -- -r .Tags[0])"
      - "nix run nixpkgs#skopeo -- copy docker-archive:$(realpath result) docker://${REGISTRY_URL}/${REGISTRY_USER}/${IMAGE_TAG} --dest-creds ${REGISTRY_USER}:${REGISTRY_PASS}"
