when:
  - event: push
    branch: main

steps:
  - name: build
    image: woodpeckerci/plugin-docker-buildx
    settings:
      platforms: linux/amd64
      repo: git.hydrar.de/jmarya/bk-k8s
      registry: git.hydrar.de
      tags: latest
      dockerfile: k8s-operator/Dockerfile
      context: k8s-operator/
      username: jmarya
      password:
        from_secret: registry_token